module.exports = {
  // SERVER_URL: 'https://cognicare-projectcode.koyeb.app',
  SERVER_URL: 'https://36d4-113-11-37-36.ngrok-free.app',
  VONAGE_SMS_API_KEY: process.env.VONAGE_SMS_API_KEY,
  VONAGE_SMS_API_SECRET: process.env.VONAGE_SMS_API_SECRET,
  VONAGE_SMS_API_OUR_NUMBER: process.env.VONAGE_SMS_API_OUR_NUMBER,
  VONAGE_TOKEN:
    'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODM5NTMxMjYsImp0aSI6ImZhZDNmZTkwLWYxNDgtMTFlZC04OTI2LWQzYWZhNWM2N2E0OCIsImFwcGxpY2F0aW9uX2lkIjoiZDdhNWUyNTQtMjA5My00NDA3LTkyYWYtNzliZjM5YjU3MTZhIn0.WEKSx9bjzrd4xeXLOWBB5PPTz9NmcbicFPiZBZT6aYZfLB3MErKXGebUV0m0GInPKuqkvsFqTAi-sFJCr7X_R-Q7nY0ZmVy5nD_vN1ZcKHLInB2QDngypOpNmDeno-kZK3rFHh8zUJlPrdK-BVZ9MDnTX78ZQ-C0W-c_Y0TveHQEb7qXmDyb0Dv6mbiRFGKf-k6v9Li7lHbxPKYIWggrkGlklvLLcgBLkZbax_MabrBDPDEGjRqRsHPlGhOI3XZ3TNGSJzO8OkfAtMY16Ba8LgZyi9tS_fEX-WFKNUnoibEVmk8C92x9GBhfo-WMlyN4LYodmnKECmFF5Wy-8LedyQ',
};
