module.exports = {
  VONAGE_SMS_API_KEY: process.env.REACT_APP_VONAGE_SMS_API_KEY,
  VONAGE_SMS_API_SECRET: process.env.REACT_APP_VONAGE_SMS_API_SECRET,
  VONAGE_SMS_API_OUR_NUMBER: process.env.REACT_APP_VONAGE_SMS_API_OUR_NUMBER,
};
